"""Shared Postgres helpers for handler upserts.

The CRM's Postgres schema is generated by Payload CMS, so all writes from the
event-processor must respect the column naming Payload uses (snake_case
flattened paths for groups, child tables for nested arrays).

The helpers here cover the two patterns every handler needs:

* :func:`upsert` — single-row INSERT … ON CONFLICT … DO UPDATE on a parent
  table keyed by a natural identifier (e.g. ``loan_account_id``,
  ``conversation_id``).
* :func:`upsert_child` — child-table upsert keyed by ``(_parent_id, key)`` for
  Payload's array-stored tables (e.g.
  ``loan_accounts_repayment_schedule_payments``).
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any, Iterable, Union

import asyncpg


def coerce_date(value: Any) -> Any:
    """Coerce a date-shaped value to ``datetime.date``/``datetime.datetime``.

    asyncpg refuses strings for ``timestamp``/``date`` columns. The Billie
    event SDKs deliver some fields (e.g. ``date_of_birth``, ``opened_date``,
    schedule payment ``due_date``) as ISO strings — coerce them defensively
    so handlers don't need to know which SDK fields are typed vs string.

    Returns the value unchanged if it's already a ``datetime``/``date``,
    ``None`` if coercion fails (caller decides whether NULL is acceptable).
    """
    if value is None or isinstance(value, (datetime, date)):
        return value
    if isinstance(value, str):
        # Strip a trailing 'Z' and try datetime first, then plain date.
        normalised = value.replace("Z", "+00:00")
        try:
            return datetime.fromisoformat(normalised)
        except ValueError:
            pass
        try:
            return date.fromisoformat(value[:10])
        except ValueError:
            return None
    return None

# Anything that exposes asyncpg's `execute` signature works here — Pool and
# Connection both implement it.
ExecuteTarget = Union[asyncpg.Pool, asyncpg.Connection]


async def upsert(
    target: ExecuteTarget,
    table: str,
    *,
    conflict_columns: list[str],
    values: dict[str, Any],
    insert_only_columns: Iterable[str] | None = None,
    do_nothing_on_conflict: bool = False,
) -> None:
    """Run ``INSERT … ON CONFLICT (cols) DO UPDATE SET …`` against ``table``.

    All keys in ``values`` are inserted. On conflict, every column listed in
    ``values`` is updated from ``EXCLUDED.<col>`` *except* those named in
    ``insert_only_columns`` (typically ``created_at``).

    Args:
        target: asyncpg pool or connection.
        table: target table name (already-quoted/qualified — caller is trusted).
        conflict_columns: natural-key columns covered by a unique constraint.
        values: column → value mapping for the INSERT.
        insert_only_columns: columns that should not be updated on conflict.
        do_nothing_on_conflict: if True, use ``DO NOTHING`` instead of
            ``DO UPDATE``. Useful for append-only insertion paths.

    Notes:
        The helper builds the SQL via simple string formatting — column names
        are never user-supplied. ``$1``/``$2``/… placeholders pass the values
        safely through asyncpg's parameter binding.
    """
    if not values:
        raise ValueError(f"upsert({table}) called with empty values")

    cols = list(values.keys())
    placeholders = ", ".join(f"${i}" for i in range(1, len(cols) + 1))
    args = [values[c] for c in cols]

    sql = (
        f'INSERT INTO {table} ({", ".join(cols)}) VALUES ({placeholders}) '
        f'ON CONFLICT ({", ".join(conflict_columns)}) '
    )

    if do_nothing_on_conflict:
        sql += "DO NOTHING"
    else:
        skip = set(insert_only_columns or ())
        update_cols = [c for c in cols if c not in skip and c not in conflict_columns]
        if not update_cols:
            sql += "DO NOTHING"
        else:
            set_clause = ", ".join(f"{c} = EXCLUDED.{c}" for c in update_cols)
            sql += f"DO UPDATE SET {set_clause}"

    await target.execute(sql, *args)


async def upsert_conversation(
    target: ExecuteTarget,
    *,
    conversation_id: str,
    set_values: dict[str, Any],
    insert_only_values: dict[str, Any] | None = None,
) -> None:
    """Upsert a conversations row, incrementing ``version`` on every conflict.

    Conversations are append-heavy projections — most handlers update one or
    two columns while bumping ``version`` so the optimistic-concurrency layer
    in the CRM stays in sync. This helper centralises the version-increment
    logic so individual handlers don't have to re-write the same SQL.
    """
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)
    base_insert: dict[str, Any] = {
        "conversation_id": conversation_id,
        "application_number": "",  # NOT NULL — overwritten if set_values has it
        "status": "active",
        "started_at": now,
        "updated_at": now,
        "created_at": now,
        "version": 1,
    }
    base_insert.update(insert_only_values or {})
    base_insert.update(set_values)
    base_insert["updated_at"] = now  # always refresh

    cols = list(base_insert.keys())
    placeholders = ", ".join(f"${i}" for i in range(1, len(cols) + 1))
    args = [base_insert[c] for c in cols]

    # Columns that the handler explicitly set — these get refreshed on conflict.
    # `conversation_id` is the conflict key (never updated). `created_at`,
    # `started_at`, defaulted `status`/`application_number`/`version` are
    # insert-only — left as-is on conflict.
    do_not_update = {"conversation_id", "created_at", "started_at", "version"}
    update_cols = [c for c in set_values.keys() if c not in do_not_update]
    update_cols.append("updated_at")
    set_clause = ", ".join(f"{c} = EXCLUDED.{c}" for c in update_cols)

    sql = (
        f'INSERT INTO conversations ({", ".join(cols)}) VALUES ({placeholders}) '
        f"ON CONFLICT (conversation_id) DO UPDATE SET "
        f"{set_clause}, version = COALESCE(conversations.version, 1) + 1"
    )
    await target.execute(sql, *args)


async def merge_jsonb(
    target: ExecuteTarget,
    table: str,
    *,
    column: str,
    key_column: str,
    key_value: Any,
    patch: dict[str, Any],
    bump_version: bool = False,
) -> None:
    """UPDATE table SET <col> = coalesce(<col>, '{}') || patch WHERE <key>.

    Used for the cluster of conversation handlers that flip individual keys
    inside the ``statement_capture`` jsonb column without a known shape.
    """
    import json

    extra = ", version = COALESCE(version, 1) + 1" if bump_version else ""
    sql = (
        f"UPDATE {table} SET {column} = COALESCE({column}, '{{}}'::jsonb) || $1::jsonb, "
        f"updated_at = NOW(){extra} WHERE {key_column} = $2"
    )
    await target.execute(sql, json.dumps(patch), key_value)


async def update_by_key(
    target: ExecuteTarget,
    table: str,
    *,
    key_column: str,
    key_value: Any,
    values: dict[str, Any],
) -> str:
    """Plain UPDATE keyed by a single column. Returns the asyncpg status string.

    Use this for status-flip events (``writeoff.approved``, etc.) where we know
    the row exists and don't need an upsert.
    """
    if not values:
        raise ValueError(f"update_by_key({table}) called with empty values")
    cols = list(values.keys())
    set_clause = ", ".join(f"{c} = ${i}" for i, c in enumerate(cols, start=1))
    args = [values[c] for c in cols]
    args.append(key_value)
    sql = (
        f"UPDATE {table} SET {set_clause} "
        f"WHERE {key_column} = ${len(cols) + 1}"
    )
    return await target.execute(sql, *args)
