# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import marketing_service_pb2 as marketing__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in marketing_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MarketingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertContact = channel.unary_unary(
            "/billie.marketing.MarketingService/UpsertContact",
            request_serializer=marketing__service__pb2.UpsertContactRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.UpsertContactResponse.FromString,
            _registered_method=True,
        )
        self.UpdateContact = channel.unary_unary(
            "/billie.marketing.MarketingService/UpdateContact",
            request_serializer=marketing__service__pb2.UpdateContactRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.CommandResponse.FromString,
            _registered_method=True,
        )
        self.SetConsent = channel.unary_unary(
            "/billie.marketing.MarketingService/SetConsent",
            request_serializer=marketing__service__pb2.SetConsentRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.CommandResponse.FromString,
            _registered_method=True,
        )
        self.LogInteraction = channel.unary_unary(
            "/billie.marketing.MarketingService/LogInteraction",
            request_serializer=marketing__service__pb2.LogInteractionRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.CommandResponse.FromString,
            _registered_method=True,
        )
        self.EraseContact = channel.unary_unary(
            "/billie.marketing.MarketingService/EraseContact",
            request_serializer=marketing__service__pb2.EraseContactRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.CommandResponse.FromString,
            _registered_method=True,
        )
        self.CreateBatch = channel.unary_unary(
            "/billie.marketing.MarketingService/CreateBatch",
            request_serializer=marketing__service__pb2.CreateBatchRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.CreateBatchResponse.FromString,
            _registered_method=True,
        )
        self.AssignBatch = channel.unary_unary(
            "/billie.marketing.MarketingService/AssignBatch",
            request_serializer=marketing__service__pb2.AssignBatchRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.AssignBatchResponse.FromString,
            _registered_method=True,
        )
        self.TriggerBatchInvitations = channel.unary_unary(
            "/billie.marketing.MarketingService/TriggerBatchInvitations",
            request_serializer=marketing__service__pb2.TriggerBatchInvitationsRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.TriggerBatchInvitationsResponse.FromString,
            _registered_method=True,
        )
        self.SubmitFeedback = channel.unary_unary(
            "/billie.marketing.MarketingService/SubmitFeedback",
            request_serializer=marketing__service__pb2.SubmitFeedbackRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.SubmitFeedbackResponse.FromString,
            _registered_method=True,
        )
        self.SetFeedbackStatus = channel.unary_unary(
            "/billie.marketing.MarketingService/SetFeedbackStatus",
            request_serializer=marketing__service__pb2.SetFeedbackStatusRequest.SerializeToString,
            response_deserializer=marketing__service__pb2.SetFeedbackStatusResponse.FromString,
            _registered_method=True,
        )


class MarketingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpsertContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LogInteraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EraseContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateBatch(self, request, context):
        """Phase 2 (Stream A) — batches + invites"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AssignBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TriggerBatchInvitations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubmitFeedback(self, request, context):
        """Phase 2 (Stream A) — feedback intake + triage"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetFeedbackStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MarketingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UpsertContact": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertContact,
            request_deserializer=marketing__service__pb2.UpsertContactRequest.FromString,
            response_serializer=marketing__service__pb2.UpsertContactResponse.SerializeToString,
        ),
        "UpdateContact": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateContact,
            request_deserializer=marketing__service__pb2.UpdateContactRequest.FromString,
            response_serializer=marketing__service__pb2.CommandResponse.SerializeToString,
        ),
        "SetConsent": grpc.unary_unary_rpc_method_handler(
            servicer.SetConsent,
            request_deserializer=marketing__service__pb2.SetConsentRequest.FromString,
            response_serializer=marketing__service__pb2.CommandResponse.SerializeToString,
        ),
        "LogInteraction": grpc.unary_unary_rpc_method_handler(
            servicer.LogInteraction,
            request_deserializer=marketing__service__pb2.LogInteractionRequest.FromString,
            response_serializer=marketing__service__pb2.CommandResponse.SerializeToString,
        ),
        "EraseContact": grpc.unary_unary_rpc_method_handler(
            servicer.EraseContact,
            request_deserializer=marketing__service__pb2.EraseContactRequest.FromString,
            response_serializer=marketing__service__pb2.CommandResponse.SerializeToString,
        ),
        "CreateBatch": grpc.unary_unary_rpc_method_handler(
            servicer.CreateBatch,
            request_deserializer=marketing__service__pb2.CreateBatchRequest.FromString,
            response_serializer=marketing__service__pb2.CreateBatchResponse.SerializeToString,
        ),
        "AssignBatch": grpc.unary_unary_rpc_method_handler(
            servicer.AssignBatch,
            request_deserializer=marketing__service__pb2.AssignBatchRequest.FromString,
            response_serializer=marketing__service__pb2.AssignBatchResponse.SerializeToString,
        ),
        "TriggerBatchInvitations": grpc.unary_unary_rpc_method_handler(
            servicer.TriggerBatchInvitations,
            request_deserializer=marketing__service__pb2.TriggerBatchInvitationsRequest.FromString,
            response_serializer=marketing__service__pb2.TriggerBatchInvitationsResponse.SerializeToString,
        ),
        "SubmitFeedback": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitFeedback,
            request_deserializer=marketing__service__pb2.SubmitFeedbackRequest.FromString,
            response_serializer=marketing__service__pb2.SubmitFeedbackResponse.SerializeToString,
        ),
        "SetFeedbackStatus": grpc.unary_unary_rpc_method_handler(
            servicer.SetFeedbackStatus,
            request_deserializer=marketing__service__pb2.SetFeedbackStatusRequest.FromString,
            response_serializer=marketing__service__pb2.SetFeedbackStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "billie.marketing.MarketingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "billie.marketing.MarketingService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MarketingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertContact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/UpsertContact",
            marketing__service__pb2.UpsertContactRequest.SerializeToString,
            marketing__service__pb2.UpsertContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateContact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/UpdateContact",
            marketing__service__pb2.UpdateContactRequest.SerializeToString,
            marketing__service__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetConsent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/SetConsent",
            marketing__service__pb2.SetConsentRequest.SerializeToString,
            marketing__service__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LogInteraction(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/LogInteraction",
            marketing__service__pb2.LogInteractionRequest.SerializeToString,
            marketing__service__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EraseContact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/EraseContact",
            marketing__service__pb2.EraseContactRequest.SerializeToString,
            marketing__service__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/CreateBatch",
            marketing__service__pb2.CreateBatchRequest.SerializeToString,
            marketing__service__pb2.CreateBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AssignBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/AssignBatch",
            marketing__service__pb2.AssignBatchRequest.SerializeToString,
            marketing__service__pb2.AssignBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TriggerBatchInvitations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/TriggerBatchInvitations",
            marketing__service__pb2.TriggerBatchInvitationsRequest.SerializeToString,
            marketing__service__pb2.TriggerBatchInvitationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitFeedback(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/SubmitFeedback",
            marketing__service__pb2.SubmitFeedbackRequest.SerializeToString,
            marketing__service__pb2.SubmitFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetFeedbackStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/billie.marketing.MarketingService/SetFeedbackStatus",
            marketing__service__pb2.SetFeedbackStatusRequest.SerializeToString,
            marketing__service__pb2.SetFeedbackStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
